# Generated by Django 3.2.7 on 2021-09-19 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('table_app', '0002_auto_20210919_1827'),
    ]

    operations = [
        migrations.AddField(
            model_name='ad',
            name='content',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='ad',
            name='title',
            field=models.CharField(max_length=64, null=True),
        ),
    ]
