# Generated by Django 3.2.7 on 2021-09-28 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ad',
            name='active',
        ),
        migrations.RemoveField(
            model_name='ad',
            name='user',
        ),
        migrations.AddField(
            model_name='ad',
            name='contact',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='ad',
            name='category',
            field=models.IntegerField(choices=[(0, 'inne'), (1, 'odzież'), (2, 'motoryzacja'), (3, 'usługi'), (4, 'żywność'), (5, 'sport'), (6, 'nauka')], default=0),
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
