# Generated by Django 3.2.7 on 2021-10-07 18:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_auto_20210928_1724'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Ad',
        ),
    ]
