# Generated by Django 3.2.7 on 2021-10-07 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('main_app', '0003_delete_ad'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64)),
                ('content', models.TextField(null=True)),
                ('category', models.IntegerField(choices=[(0, 'inne'), (1, 'odzież'), (2, 'motoryzacja'), (3, 'usługi'), (4, 'żywność'), (5, 'sport'), (6, 'nauka')], default=0)),
                ('contact', models.TextField()),
                ('password', models.CharField(max_length=64)),
            ],
        ),
    ]
